name: virtual_tour_webview
description: "Welcome to the Virtual Tour Demo App! This Flutter project is designed to provide an immersive experience, simulating a customized version of Google Earth."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
#  webview_flutter: ^4.9.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loader.gif
  fonts:
    - family: TiltNeon
      fonts:
        - asset: assets/fonts/TiltNeon-Regular.ttf